title: "[dApps] <Title>"
labels: ["dApp"]
body:
  - type: markdown
    attributes:
      value: |
        ## Check the docs!
        Before proceeding, please check the Disclaimer.

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - 
        - DeFi
        - NFT
        - Infrastructure
        - Wallet
    validations:
      required: true
      
  - type: textarea
    id: dapp-description
    attributes:
      label: Provide a brief description of the dApp.
    validations:
      required: true
      
  - type: textarea
    id: specific-issue
    attributes:
      label: What is the specific issue or error you're encountering?
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Can you share the error messages or logs you're receiving, if any?
    validations:
      required: true

  - type: textarea
    id: recent-changes
    attributes:
      label: Have you made any recent changes to the contract before encountering this issue?
    validations:
      required: true

  - type: textarea
    id: external-libraries
    attributes:
      label: Are there any external libraries or contracts that your contract interacts with?
    validations:
      required: true

  - type: textarea
    id: contract-code
    attributes:
      label: Can you provide the relevant portions of your contract code where the issue is occurring?
    validations:
      required: true

  - type: textarea
    id: isolation-results
    attributes:
      label: Have you tried to isolate the problem, and if so, what were the results?
    validations:
      required: true

  - type: textarea
    id: resolution-steps
    attributes:
      label: What steps have you already taken to try to resolve the issue?
    validations:
      required: true

  - type: input
    id: repo-link
    attributes:
      label: Repo Link (Optional)
      description: If applicable, please provide a link to a repo
    validations:
      required: false
      
  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: If applicable, please provide any additional details
    validations:
      required: false
